# Generated by Django 3.2.5 on 2021-07-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('is_mini', models.BooleanField(default=False)),
                ('number_of_tiles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='datetime game started')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='datetime game ended')),
                ('total_time', models.IntegerField(blank=True, help_text='Number of seconds the game lasted for.', null=True)),
                ('avg_seconds_per_turn', models.IntegerField(blank=True, help_text='Number of seconds of the average turn.', null=True)),
                ('total_number_of_tiles', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('wins', models.IntegerField(default=0)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, help_text='Percentage of games won', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('PINK', 'Pink'), ('GREEN', 'Green'), ('BLACK', 'Black')], max_length=7)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='website.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to='website.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='players', through='website.PlayerInGame', to='website.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(blank=True, to='website.Image'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.player'),
        ),
        migrations.CreateModel(
            name='ExpansionInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_rules', models.BooleanField()),
                ('use_tiles', models.BooleanField(default=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expansion_games', to='website.expansion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_expansions', to='website.game')),
            ],
        ),
        migrations.AddField(
            model_name='expansion',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='expansions', through='website.ExpansionInGame', to='website.Game'),
        ),
    ]
