# Generated by Django 3.2.5 on 2021-08-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expansioningame',
            name='expansion_only_once_per_game',
        ),
    ]
