# Generated by Django 3.2.5 on 2021-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finalised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='expansioningame',
            constraint=models.UniqueConstraint(fields=('expansion', 'game'), name='expansion_only_once_per_game'),
        ),
    ]
