# Generated by Django 3.2.5 on 2021-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210730_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
