# Generated by Django 3.2.5 on 2021-08-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_expansioningame_expansion_only_once_per_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expansion',
            options={'ordering': ['is_mini', 'name', 'number_of_tiles']},
        ),
    ]
