# Generated by Django 3.2.5 on 2021-07-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_playeringame_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='playeringame',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='player_only_once_per_game'),
        ),
    ]
