# Generated by Django 3.2.5 on 2021-09-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_expansion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
    ]
