# Generated by Django 3.2.5 on 2021-09-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_playeringame_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='draw',
            field=models.BooleanField(default=False),
        ),
    ]
